USE DATABASE DEMO_DATABASE;

---1. LOADED THE DATA BY SETTING ORDER_DATE AS PRIMARY KEY

CREATE OR REPLACE TABLE SALES_DATA_FINAL
(
 ORDER_ID VARCHAR (80),
 ORDER_DATE DATE PRIMARY KEY NOT NULL,
 SHIP_DATE DATE NOT NULL,-----3. ORDER_DATE AND SHIP_DATE DATA TYPE SHOULD BE DATE (CLEANED THESE TWO COLUMNS IN THE CSV FILE BEFORE LOADING)
 SHIP_MODE VARCHAR (100),
 CUSTOMER_NAME VARCHAR (100),
 SEGMENT VARCHAR (20),
 STATE VARCHAR (100),
 COUNTRY VARCHAR (50),
 MARKET VARCHAR (20),
 REGION VARCHAR (100),
 PRODUCT_ID VARCHAR (40),
 CATEGORY VARCHAR (50),
 SUB_CATEGORY VARCHAR(30),
 PRODUCT_NAME VARCHAR(200),
 SALES NUMBER,
 QUANTITY INTEGER,
 DISCOUNT NUMBER (5,2),
 PROFIT NUMBER (10,5),
 SHIPPING NUMBER (10,3),
 ORDER_PRIORITY VARCHAR (100),
 YEAR INTEGER
);
DESCRIBE TABLE SALES_DATA_FINAL;

SELECT * FROM SALES_DATA_FINAL;

---2. Change the Primary key to Order Id Column:

ALTER TABLE SALES_DATA_FINAL
DROP PRIMARY KEY;

ALTER TABLE SALES_DATA_FINAL
ADD PRIMARY KEY(ORDER_ID);


----4. Create a new column called order_extract and extract the number after the last ‘–‘from Order ID column.

SELECT SUBSTR (ORDER_ID,9,15) AS ORDER_EXTRACT
FROM SALES_DATA_FINAL;


----5. Create a new column called Discount Flag and categorize it based on discount. Use ‘Yes’ if the discount is greater than zero else ‘No’.

SELECT *,
         CASE 
             WHEN DISCOUNT >0 THEN 'YES'
             ELSE 'NO'
         END AS DISCOUNT_FLAG
FROM SALES_DATA_FINAL;

---6. Create a new column called process days and calculate how many days it takes for each order id to process from the order to its shipment.

SELECT *, DATEDIFF ('DAY',ORDER_DATE,SHIP_DATE) AS PROCESS_DAYS
FROM SALES_DATA_FINAL;

/*
7. FLAG THE PROCESS DAY AS BY RATING IF IT TAKES LESS OR EQUAL 3 DAYS MAKE 5,
LESS OR EQUAL THAN 6 DAYS BUT MORE THAN 3 MAKE 4,
LESS THAN 10 BUT MORE THAN 6 MAKE 3,
MORE THAN 10 MAKE IT 2 FOR EVERY ORDER ID.
*/

SELECT *,
         CASE
             WHEN DATEDIFF ('DAY',ORDER_DATE,SHIP_DATE) <= '3' THEN '5'
             WHEN DATEDIFF ('DAY',ORDER_DATE,SHIP_DATE) <='6' AND DATEDIFF ('DAY',ORDER_DATE,SHIP_DATE) >'3' THEN '4'
             WHEN DATEDIFF ('DAY',ORDER_DATE,SHIP_DATE) <'10' AND DATEDIFF ('DAY',ORDER_DATE,SHIP_DATE) >'6' THEN '3'
             ELSE '2'
         END AS PROCESSING_RATING
FROM SALES_DATA_FINAL;